[package]
name = "app"
version = "0.1.8"
description = "A simple file explorer"
authors = ["Ricky Dane Perlick"]
license = "none"
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.73"

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
chrono = "0.4.26"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.1", features = [ "protocol-asset", "path-all", "window-all", "dialog-all", "fs-all"] }
open = "5.0.0"
rust_search = "2.1.0"
stopwatch = "0.0.7"
base64 = "0.21.2"
zip = "0.6.6"
zip-extensions = "0.6.1"
rar = "0.2.0"
sevenz-rust = "0.5.2"
dialog = "0.3.0"
copy_dir = "0.1.3"
unrar = "0.5.1"
dateparser = "0.2.0"
get_sys_info = "0.1.21"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
